const HANDLE_SUBMIT = "HANDLE_SUBMIT"
const TOGGLE_FORM = "TOGGLE_FORM"
const EMAIL_CHANGE = 'EMAIL_CHANGE'
const PASSWORD_CHANGE = 'PASSWORD_CHANGE'
const LOGOUT = 'LOGOUT'

const actions = {HANDLE_SUBMIT, TOGGLE_FORM, PASSWORD_CHANGE, EMAIL_CHANGE, LOGOUT}

export default actions
